[package]
name = "mobiumata-ws2812"
version = "0.1.0"
edition = "2021"

[dependencies]
embedded-graphics = { version = "0.8.1" }
embedded-graphics-core = { version = "0.4.0" }
embassy-rp = "0.1.0"
embassy-time = "0.3.0"
fixed-macro = "1.2.0"
fixed = "1.27.0"
pio = "0.2.1"
